<a href="https://colab.research.google.com/github/Riochin/Zerokara-Deep-Learning/blob/main/3_3__multidimensional_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3.3 多次元配列の計算

In [1]:
import numpy as np
A = np.array([1,2,3,4])
print(A)

np.ndim(A)
A.shape # shapeで 行*列がタプル型で出力される
A.shape[0]

[1 2 3 4]


4

In [4]:
B = np.array([[1,2],[3,4],[5,6]])
print(B)

np.ndim(B)
B.shape  # 3 * 2の配列であるので、(3,2)

[[1 2]
 [3 4]
 [5 6]]


(3, 2)

## 3.3.2 行列の積

In [6]:
A = np.array([[1,2],[3,4]])
A.shape

B = np.array([[5,6],[7,8]])

np.dot(A,B) # dot -> ドット積

array([[19, 22],
       [43, 50]])

In [7]:
A = np.array([[1,2,3], [4,5,6]])
A.shape

B = np.array([[1,2], [3,4], [5,6]])
B.shape

np.dot(A,B)

array([[22, 28],
       [49, 64]])

In [8]:
# １要素目の列と２要素目の行が同じじゃないとエラー

C = np.array([[1,2], [3,4]])
C.shape
A.shape
np.dot(A, C)

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

## 3.3.3 ニューラルネットワークの行列の積
> np.dotを使ってYの結果を一気に計算できる。

In [9]:
X = np.array([1,2])
X .shape # (2,)

W = np.array([[1,3,5],[2,4,6]])
print(W)
W.shape # (2,3)

Y = np.dot(X,W)
print(Y)

[[1 3 5]
 [2 4 6]]
[ 5 11 17]
